CREATE TABLE casbin_rule
(
    id    int UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ptype varchar(100) NULL,
    v0    varchar(100) NULL,
    v1    varchar(100) NULL,
    v2    varchar(100) NULL,
    v3    varchar(100) NULL,
    v4    varchar(100) NULL,
    v5    varchar(100) NULL,
    CONSTRAINT idx_casbin_rule UNIQUE (ptype, v0, v1, v2, v3, v4, v5)
);

INSERT INTO ag_menu (id, created_at, updated_at, deleted_at, name, path, method, type, icon, parent_id, order_id)
VALUES (1, NOW(), NOW(), null, '看板', '/dashboard', 'GET', 2, 'HomeOutlined', 0, 100),
       (2, NOW(), NOW(), null, '设置', '/settings', '-', 1, 'SettingOutlined', 0, 9000),
       (3, NOW(), NOW(), null, '用户管理', '/settings/users', 'GET', 2, 'UserOutlined', 2, 9001),
       (4, NOW(), NOW(), null, '分组管理', '/settings/groups', 'GET', 2, 'TeamOutlined', 2, 9002),
       (5, NOW(), NOW(), null, '角色管理', '/settings/roles', 'GET', 2, 'ContactsOutlined', 2, 9003),
       (6, NOW(), NOW(), null, '菜单管理', '/settings/menus', 'GET', 2, 'ApartmentOutlined', 2, 9004),
       (7, NOW(), NOW(), null, '系统设置', '/settings/system', 'GET', 2, 'HomeOutlined', 2, 9005),
       (8, NOW(), NOW(), null, '创建用户', '/api/v1/users', 'POST', 3, '', 3, 0),
       (9, NOW(), NOW(), null, '修改用户', '/api/v1/users/:id', 'PUT', 3, '', 3, 0),
       (10, NOW(), NOW(), null, '删除用户', '/api/v1/users', 'DELETE', 3, '', 3, 0),
       (11, NOW(), NOW(), null, '用户列表', '/api/v1/users', 'GET', 3, '', 3, 0),
       (12, NOW(), NOW(), null, '创建分组', '/api/v1/groups', 'POST', 3, '', 4, 0),
       (13, NOW(), NOW(), null, '修改分组', '/api/v1/groups/:id', 'PUT', 3, '', 4, 0),
       (14, NOW(), NOW(), null, '删除分组', '/api/v1/groups/:id', 'DELETE', 3, '', 4, 0),
       (15, NOW(), NOW(), null, '分组列表', '/api/v1/groups', 'GET', 3, '', 4, 0),
       (16, NOW(), NOW(), null, '分组详情', '/api/v1/groups/:id', 'GET', 3, '', 4, 0),
       (17, NOW(), NOW(), null, '创建角色', '/api/v1/roles', 'POST', 3, '', 5, 0),
       (18, NOW(), NOW(), null, '修改角色', '/api/v1/roles/:id', 'PUT', 3, '', 5, 0),
       (19, NOW(), NOW(), null, '删除角色', '/api/v1/roles/:id', 'DELETE', 3, '', 5, 0),
       (20, NOW(), NOW(), null, '角色列表', '/api/v1/roles', 'GET', 3, '', 5, 0),
       (21, NOW(), NOW(), null, '创建菜单', '/api/v1/menus', 'POST', 3, '', 6, 0),
       (22, NOW(), NOW(), null, '修改菜单', '/api/v1/menus/:id', 'PUT', 3, '', 6, 0),
       (23, NOW(), NOW(), null, '删除菜单', '/api/v1/menus/:id', 'DELETE', 3, '', 6, 0),
       (24, NOW(), NOW(), null, '菜单列表', '/api/v1/menus', 'GET', 3, '', 6, 0),
       (25, NOW(), NOW(), null, '修改权限', '/api/v1/roles/:id/menus', 'PUT', 3, '', 6, 0),
       (26, NOW(), NOW(), null, '权限列表', '/api/v1/roles/:id/menus', 'GET', 3, '', 6, 0),
       (27, NOW(), NOW(), null, '菜单详情', '/api/v1/menus/:id', 'GET', 3, '', 6, 0);

INSERT INTO casbin_rule (id, ptype, v0, v1, v2, v3, v4, v5)
VALUES (1, 'p', 'action::1', '/dashboard', 'GET', '', '', ''),
       (2, 'p', 'action::3', '/settings/users', 'GET', '', '', ''),
       (3, 'p', 'action::8', '/api/v1/users', 'POST', '', '', ''),
       (4, 'p', 'action::9', '/api/v1/users/:id', 'PUT', '', '', ''),
       (5, 'p', 'action::10', '/api/v1/users/:id', 'DELETE', '', '', ''),
       (6, 'p', 'action::11', '/api/v1/users', 'GET', '', '', ''),
       (7, 'p', 'action::4', '/settings/groups', 'GET', '', '', ''),
       (8, 'p', 'action::12', '/api/v1/groups', 'POST', '', '', ''),
       (9, 'p', 'action::13', '/api/v1/groups/:id', 'PUT', '', '', ''),
       (10, 'p', 'action::14', '/api/v1/groups/:id', 'DELETE', '', '', ''),
       (11, 'p', 'action::15', '/api/v1/groups', 'GET', '', '', ''),
       (12, 'p', 'action::16', '/api/v1/groups/:id', 'GET', '', '', ''),
       (13, 'p', 'action::5', '/settings/roles', 'GET', '', '', ''),
       (14, 'p', 'action::17', '/api/v1/roles', 'POST', '', '', ''),
       (15, 'p', 'action::18', '/api/v1/roles/:id', 'PUT', '', '', ''),
       (16, 'p', 'action::19', '/api/v1/roles/:id', 'DELETE', '', '', ''),
       (17, 'p', 'action::20', '/api/v1/roles', 'GET', '', '', ''),
       (18, 'p', 'action::6', '/settings/menus', 'GET', '', '', ''),
       (19, 'p', 'action::21', '/api/v1/menus', 'POST', '', '', ''),
       (20, 'p', 'action::22', '/api/v1/menus/:id', 'PUT', '', '', ''),
       (21, 'p', 'action::23', '/api/v1/menus/:id', 'DELETE', '', '', ''),
       (22, 'p', 'action::24', '/api/v1/menus', 'GET', '', '', ''),
       (23, 'p', 'action::25', '/api/v1/roles/:id/menus', 'PUT', '', '', ''),
       (24, 'p', 'action::26', '/api/v1/roles/:id/menus', 'GET', '', '', ''),
       (25, 'p', 'action::27', '/api/v1/menus/:id', 'GET', '', '', ''),
       (26, 'p', 'action::7', '/settings/system', 'GET', '', '', ''),
       (27, 'g', 'role::1', 'action::1', '', '', '', ''),
       (28, 'g', 'role::1', 'action::2', '', '', '', ''),
       (29, 'g', 'role::1', 'action::3', '', '', '', ''),
       (30, 'g', 'role::1', 'action::4', '', '', '', ''),
       (31, 'g', 'role::1', 'action::5', '', '', '', ''),
       (32, 'g', 'role::1', 'action::6', '', '', '', ''),
       (33, 'g', 'role::1', 'action::7', '', '', '', ''),
       (34, 'g', 'role::1', 'action::8', '', '', '', ''),
       (35, 'g', 'role::1', 'action::9', '', '', '', ''),
       (36, 'g', 'role::1', 'action::10', '', '', '', ''),
       (37, 'g', 'role::1', 'action::11', '', '', '', ''),
       (38, 'g', 'role::1', 'action::12', '', '', '', ''),
       (39, 'g', 'role::1', 'action::13', '', '', '', ''),
       (40, 'g', 'role::1', 'action::14', '', '', '', ''),
       (41, 'g', 'role::1', 'action::15', '', '', '', ''),
       (42, 'g', 'role::1', 'action::16', '', '', '', ''),
       (43, 'g', 'role::1', 'action::17', '', '', '', ''),
       (44, 'g', 'role::1', 'action::18', '', '', '', ''),
       (45, 'g', 'role::1', 'action::19', '', '', '', ''),
       (46, 'g', 'role::1', 'action::20', '', '', '', ''),
       (47, 'g', 'role::1', 'action::21', '', '', '', ''),
       (48, 'g', 'role::1', 'action::22', '', '', '', ''),
       (49, 'g', 'role::1', 'action::23', '', '', '', ''),
       (50, 'g', 'role::1', 'action::24', '', '', '', ''),
       (51, 'g', 'role::1', 'action::25', '', '', '', ''),
       (52, 'g', 'role::1', 'action::26', '', '', '', ''),
       (53, 'g', 'role::1', 'action::27', '', '', '', ''),
       (54, 'g', 'role::2', 'action::1', '', '', '', ''),
       (55, 'g', 'user::1', 'role::1', '', '', '', ''),
       (56, 'g', 'group::1', 'role::2', '', '', '', '');

INSERT INTO ag_role_menu (id, created_at, updated_at, deleted_at, role_id, menu_id)
VALUES (1, NOW(), NOW(), null, 1, 1),
       (2, NOW(), NOW(), null, 1, 2),
       (3, NOW(), NOW(), null, 1, 3),
       (4, NOW(), NOW(), null, 1, 4),
       (5, NOW(), NOW(), null, 1, 5),
       (6, NOW(), NOW(), null, 1, 6),
       (7, NOW(), NOW(), null, 1, 7),
       (8, NOW(), NOW(), null, 1, 8),
       (9, NOW(), NOW(), null, 1, 9),
       (10, NOW(), NOW(), null, 1, 10),
       (11, NOW(), NOW(), null, 1, 11),
       (12, NOW(), NOW(), null, 1, 12),
       (13, NOW(), NOW(), null, 1, 13),
       (14, NOW(), NOW(), null, 1, 14),
       (15, NOW(), NOW(), null, 1, 15),
       (16, NOW(), NOW(), null, 1, 16),
       (17, NOW(), NOW(), null, 1, 17),
       (18, NOW(), NOW(), null, 1, 18),
       (19, NOW(), NOW(), null, 1, 19),
       (20, NOW(), NOW(), null, 1, 20),
       (21, NOW(), NOW(), null, 1, 21),
       (22, NOW(), NOW(), null, 1, 22),
       (23, NOW(), NOW(), null, 1, 23),
       (24, NOW(), NOW(), null, 1, 24),
       (25, NOW(), NOW(), null, 1, 25),
       (26, NOW(), NOW(), null, 1, 26),
       (27, NOW(), NOW(), null, 1, 27),
       (28, NOW(), NOW(), null, 1, 28),
       (29, NOW(), NOW(), null, 1, 29),
       (30, NOW(), NOW(), null, 1, 30),
       (31, NOW(), NOW(), null, 1, 31),
       (32, NOW(), NOW(), null, 1, 32),
       (33, NOW(), NOW(), null, 1, 33),
       (34, NOW(), NOW(), null, 1, 34),
       (35, NOW(), NOW(), null, 1, 35),
       (36, NOW(), NOW(), null, 1, 36),
       (37, NOW(), NOW(), null, 1, 37),
       (38, NOW(), NOW(), null, 1, 38),
       (39, NOW(), NOW(), null, 1, 39),
       (40, NOW(), NOW(), null, 1, 40),
       (41, NOW(), NOW(), null, 1, 41),
       (42, NOW(), NOW(), null, 1, 42),
       (43, NOW(), NOW(), null, 1, 43),
       (44, NOW(), NOW(), null, 1, 44),
       (45, NOW(), NOW(), null, 1, 45),
       (46, NOW(), NOW(), null, 1, 46),
       (47, NOW(), NOW(), null, 1, 47),
       (48, NOW(), NOW(), null, 1, 48),
       (49, NOW(), NOW(), null, 1, 49),
       (50, NOW(), NOW(), null, 1, 50),
       (51, NOW(), NOW(), null, 1, 51),
       (52, NOW(), NOW(), null, 1, 52),
       (53, NOW(), NOW(), null, 1, 53),
       (54, NOW(), NOW(), null, 1, 54),
       (55, NOW(), NOW(), null, 1, 55),
       (56, NOW(), NOW(), null, 1, 56),
       (57, NOW(), NOW(), null, 1, 57),
       (58, NOW(), NOW(), null, 1, 58),
       (59, NOW(), NOW(), null, 1, 59),
       (60, NOW(), NOW(), null, 1, 60),
       (61, NOW(), NOW(), null, 1, 61),
       (62, NOW(), NOW(), null, 1, 62),
       (63, NOW(), NOW(), null, 2, 1);

INSERT INTO ag_group_role (id, created_at, updated_at, deleted_at, group_id, role_id)
VALUES (1, NOW(), NOW(), null, 1, 2);

INSERT INTO ag_group (id, created_at, updated_at, deleted_at, name)
VALUES (1, NOW(), NOW(), null, '默认分组');

INSERT INTO ag_role (id, created_at, updated_at, deleted_at, name)
VALUES (1, NOW(), NOW(), null, '超级管理员'),
       (2, NOW(), NOW(), null, '默认角色');

INSERT INTO ag_user_group (id, created_at, updated_at, deleted_at, user_id, group_id)
VALUES (1, NOW(), NOW(), null, 1, 1);

INSERT INTO ag_user_role (id, created_at, updated_at, deleted_at, user_id, role_id)
VALUES (1, NOW(), NOW(), null, 1, 1);

INSERT INTO ag_user (id, created_at, updated_at, deleted_at, username, password, email, status)
VALUES (1, NOW(), NOW(), null, 'admin', '$2a$10$JUSPUULMMK4kOq.vchHmIemTPRZ5NEKgcntEOwG/hMt5IoyV6L89.','admin@magi.system', 1);
