version: '3'

services:

  mysql:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "root"
      MYSQL_DATABASE: "admin-go"
    volumes:
      - ./mysql/config/my.cnf:/etc/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d/
    networks:
      - default
    expose:
      - "13306"
    ports:
      - "13306:3306"

  admin-go:
    image: ghcr.io/basefas/admin-go:v0.1.0
    volumes:
      - ./config/app-config.yaml:/usr/src/app/config/app-config.yaml
    depends_on:
      - mysql
    restart: always
    networks:
      - default
    ports:
      - "8086:8086"

  react-antd-admin:
    image: ghcr.io/basefas/react-antd-admin:v0.1.0
    depends_on:
      - admin-go
    restart: always
    networks:
      - default
    ports:
      - "3003:80"